name: codeforces-cli
version: 0.1.0
synopsis: Command line interface to interact with Codeforces.
description:
  Please see the README on GitHub at
  <https://github.com/farbodsz/codeforces-cli#readme>
category: CLI
github: "farbodsz/codeforces-cli"
license: MIT
author: "Farbod Salamat-Zadeh"
copyright: "2021 Farbod Salamat-Zadeh"
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - ansi-terminal
  - base16-bytestring
  - bytestring
  - containers
  - cryptohash-sha512
  - directory
  - extra
  - http-client
  - http-conduit
  - http-types
  - open-browser
  - optparse-applicative
  - random
  - text
  - time
  - transformers

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  cf:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - codeforces-cli
