name: codeforces-cli
version: 0.1.0.0
github: "farbodsz/codeforces-cli"
license: MIT
author: "Farbod Salamat-Zadeh"
copyright: "2021 Farbod Salamat-Zadeh"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Please see the README on GitHub at
  <https://github.com/farbodsz/codeforces-cli#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - http-conduit

default-extensions:
  - OverloadedStrings
  - ScopedTypeVariables

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  cf-cli:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - codeforces-cli
