resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/17/10.yaml

packages:
  - .

extra-deps:
  - cryptohash-sha512-0.11.100.1@sha256:8279dab0daa2ffaeb0b1a9da02de780f1c19cb0a898241daa2d4d673f5c89b31,4415
